---
- name: Installer WireGuard selon le système
  ansible.builtin.package:
    name:
      - wireguard
      - wireguard-tools
    state: present
  become: true

- name: Vérifier que le module kernel WireGuard est disponible
  ansible.builtin.command: modprobe wireguard
  register: modprobe_result
  failed_when: modprobe_result.rc not in [0, 1]
  changed_when: false

- name: Activer le service wg-quick au démarrage (si applicable)
  ansible.builtin.systemd:
    name: "wg-quick@wg0"
    enabled: true
  ignore_errors: true