---
- name: Vérifier que l’interface WireGuard est bien montée
  ansible.builtin.command: ip link show {{ wg_interface }}
  register: wg_iface
  failed_when: "'UP' not in wg_iface.stdout"
  changed_when: false

- name: Afficher l’état de l’interface WireGuard
  ansible.builtin.debug:
    msg: "{{ wg_iface.stdout }}"


- name: Vérifier la configuration WireGuard active
  ansible.builtin.command: wg show {{ wg_interface }}
  register: wg_show
  changed_when: false

- name: Afficher la configuration WireGuard active
  ansible.builtin.debug:
    msg: |
      Interface : {{ wg_interface }}
      Configuration active :
      {{ wg_show.stdout }}